### ISSUE TITLE
nit: github link broken

### ISSUE THREAD

**Issue by bnewbold** [inveniosoftware/citeproc-py-styles#10]
Hello, and thank you for maintaining `citeproc-py`!

I noticed that the github repository link (what you see near the top of <https://github.com/inveniosoftware/citeproc-py-styles>) is a broken link to read the docs. It should probably be removed?

    https://citeproc-py-styles.readthedocs.io/

**Comment by jorikvankemenade** [comment]
I can't find any links to readthedocs and all links in the README seem to be correct. If I missed the link, please reopen the issue with a more precise location.

**Comment by slint** [comment]
Closed in favor of #13

**Comment by bnewbold** [comment]
Sorry I wasn't clear, and didn't reply earlier: the broken link is in the github metadata, not in the README or any other files in the repo itself. Github allows a description ("CSL styles for citeproc-py. ") and URL for each repo.

Somebody with github permissions for this repository can change (or just remove) the link by clicking the "edit" button to the right of this text.
